### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [joyhughes/Jen#104]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by alishasingh06** [comment]
@joyhughes please assign this task to me

**Comment by alishasingh06** [comment]
> guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

CONTRIBUITNG.md serves as a guide to the contributors on how to engage with the project effectively. It outlines the guidelines, coding standards, and procedures for submitting the pull requests.

**Comment by joyhughes** [comment]
This sounds good. I will assign you the issue and tag it properly...

**Comment by joyhughes** [comment]
@alishasingh06 This file should include a "best practices" section that includes the following:

1. All PRs must pass CI/CD test (issue #101 )
2. All PRs must be reviewed by a mentor or PA. At a minimum, review should include building the project, a brief test of functionality. (Some past PR reviews did not meet this standard so I am asking reviewers including myself to up their game.)
3. Once mentor has completed their review they can refer it to PA for final approval.

**Comment by suhanipaliwal** [comment]
Could you assign this issue to me as well because I was the one who raised this issue initially.

**Comment by alishasingh06** [comment]
> @alishasingh06 This file should include a "best practices" section that includes the following:
> 
> 1. All PRs must pass CI/CD test (issue [we need CICD #101](https://github.com/joyhughes/Jen/issues/101) )
> 2. All PRs must be reviewed by a mentor or PA. At a minimum, review should include building the project, a brief test of functionality. (Some past PR reviews did not meet this standard so I am asking reviewers including myself to up their game.)
> 3. Once mentor has completed their review they can refer it to PA for final approval.

PR done, please check and merge

**Comment by joyhughes** [comment]
Thanks! I will be reviewing later today (west coast USA time)
