### ISSUE TITLE
readme.md file lacks the pull request steps

### ISSUE THREAD

**Issue by prajwaldp223** [joyhughes/Jen#112]
the file lacks with the pull request steps , so that it can help the  beginners to contribute to the project

**Comment by ryukaizen** [comment]
>the file lacks with the pull request steps , so that it can help the beginners to contribute to the project
@prajwaldp223 have you read CONTRIBUTING.md?

I think we need to link CONTRIBUTING.md in the project's README @joyhughes?

**Comment by joyhughes** [comment]
> > the file lacks with the pull request steps , so that it can help the beginners to contribute to the project
> 
> @prajwaldp223 have you read CONTRIBUTING.md?
> 
> I think we need to link CONTRIBUTING.md in the project's README @joyhughes?

Yes @ryukaizen we should do this. We should also link code of conduct and LEARN.md once it exists. Do you want to make an issue and PR for this?

**Comment by ryukaizen** [comment]
Cool, I'll put a PR once you finish creating LEARN.md then! @joyhughes
