### ISSUE TITLE
Default dark mode

### ISSUE THREAD

**Issue by joyhughes** [joyhughes/Jen#116]
Add a gear icon to the right of the media controller. Use a pull-down menu to toggle dark mode. Later there will be more on the menu but right now only dark mode. Dark mode is enabled by default.

**Comment by NaunihalSingh40** [comment]
Hi @joyhughes Naunihal Singh this side from Gssoc, making dark mode the default one is a great task to do.
I request you to assign this task to me.

I will be glad to have this opportunity!

**Comment by joyhughes** [comment]
@NaunihalSingh40 
Assigned to you
Learn more about project here: https://www.youtube.com/watch?v=vN1ApdESIrc

**Comment by NaunihalSingh40** [comment]
I have tried doing it but some components color wont change even after the class names are the same as required at console,
here's a preview:

https://github.com/joyhughes/Jen/assets/109708929/13170545-bd45-4dae-893d-4217797e6205

**Comment by joyhughes** [comment]
> I have tried doing it but some components color wont change even after the class names are the same as required at console, here's a preview:
> d.mode.mp4

I will look at this during the day (night time in India) today and advise you.

**Comment by joyhughes** [comment]
Are you familiar with MUI (Material UI)? I believe you will need to set the palette mode:
https://mui.com/material-ui/customization/dark-mode/

**Comment by joyhughes** [comment]
If you have any questions or need help let me know - I will work with you on this issue.

**Comment by joyhughes** [comment]
Join the Lux Vitae discord channel https://discord.gg/EmmfUEeA

**Comment by joyhughes** [comment]
@NaunihalSingh40 Watch the Lux Vitae video https://www.youtube.com/watch?v=vN1ApdESIrc

**Comment by joyhughes** [comment]
Congratulations on your success! You may submit a PR.

**Comment by NaunihalSingh40** [comment]
is it done? if any other issue to work upon you may convey me for the same.
