### ISSUE TITLE
Add video to documentation files

### ISSUE THREAD

**Issue by joyhughes** [joyhughes/Jen#119]
Add this video to files such as README.md, LEARN.md, CONTRIBUTING.md
https://www.youtube.com/watch?v=vN1ApdESIrc

**Comment by ryukaizen** [comment]
I'm ready to get assigned on this issue @joyhughes!

**Comment by kyra-09** [comment]
Hey , @joyhughes 
Participation Role :- Contributor/GSSOC-2024

**Kindly assign this issue to me**

**Comment by joyhughes** [comment]
> I'm ready to get assigned on this issue @joyhughes!

Done  - issue is assigned

**Comment by joyhughes** [comment]
Join the Lux Vitae discord channel https://discord.gg/EmmfUEeA

**Comment by ryukaizen** [comment]
@joyhughes the invite link seems to be expired(?)
