### ISSUE TITLE
Pull Request and Issue Template Creation, GitHub Desktop Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [joyhughes/Jen#123]
I am writing to express my interest in contributing to your repository by creating a pull request template. 
I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests. 
Could you please assign me the issue under gssoc24? I am excited about the opportunity to contribute to your project and help improve the workflow for all contributors.

**Comment by joyhughes** [comment]
This sounds great. How about both pull request template and issue template?

**Comment by joyhughes** [comment]
I rolled in the Github Desktop instructions you proposed as well to this issue.

**Comment by joyhughes** [comment]
Join the Lux Vitae discord channel https://discord.gg/EmmfUEeA

**Comment by joyhughes** [comment]
Watch the Lux Vitae video https://www.youtube.com/watch?v=vN1ApdESIrc

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by joyhughes** [comment]
@PradnyaGaitonde Please join Lux Vitae discord https://discord.gg/GQQHUbkf
