### ISSUE TITLE
Fermat Spiral Vector and Warp Fields

### ISSUE THREAD

**Issue by joyhughes** [joyhughes/Jen#141]
Create a spiral vector field such that advecting from any point will produce a Fibonacci spiral. This will be used in the Kaleidoswirl scene ( issue #140 ) and for targeting warps in cellular automata.

**Comment by kairveeehh** [comment]
@joyhughes  would like to work on it as a problem solving enthusiast under gssoc'24 but need to know whether you want just the c++ implementation of the field or smt else?

**Comment by vinay-sagar123** [comment]
hello sir, can you assign this issue to me. I have started work on it.

**Comment by lassmara** [comment]
please assign me this issue

**Comment by joyhughes** [comment]
> @joyhughes would like to work on it as a problem solving enthusiast under gssoc'24 but need to know whether you want just the c++ implementation of the field or smt else?

It is C++ implementation of vector field as well as creating an effect that can be stored in the scene, and a scene file for testing.

**Comment by joyhughes** [comment]
> hello sir, can you assign this issue to me. I have started work on it.

Interesting! What have you done so far?

**Comment by kairveeehh** [comment]
> > hello sir, can you assign this issue to me. I have started work on it.
> 
> Interesting! What have you done so far?
> 

i have the complete code ready in c++ please tell me how it needs to be added just

**Comment by kairveeehh** [comment]
no I mean I have a c++ code that works on input /output based ready , can share or create a PR of the same but I need you to explain how it needs to be added

**Comment by joyhughes** [comment]
> no I mean I have a c++ code that works on input /output based ready , can share or create a PR of the same but I need you to explain how it needs to be added

I'm interested in seeing what you've written so far.

Calculations for vector fields happen in the vftools class in vector_field.cpp ... then an effect functor in effect.cpp with harness functors for each parameter that can be changed. A smart pointer to the effect functor needs to be added to any_effect.hpp and a line for loading the function needs to go into scene_io.cpp. The kaleido.json scene file can be modified to test.

**Comment by kairveeehh** [comment]
Yea this was what i needed right now I have a c++ code that generates a Fibonacci spiral upon execution will add it to Pr

**Comment by joyhughes** [comment]
> Yea this was what i needed right now I have a c++ code that generates a Fibonacci spiral upon execution will add it to Pr

Did you have a chance to take a look at it?

**Comment by kairveeehh** [comment]
> > Yea this was what i needed right now I have a c++ code that generates a Fibonacci spiral upon execution will add it to Pr
> 
> Did you have a chance to take a look at it?

yea I did but I want to ask that I am just adding a c++ code right now is that fine ?

**Comment by joyhughes** [comment]
Yes I can handle the scene file JSON
________________________________

**Comment by joyhughes** [comment]
@kairveeehh do you have any more questions about this?

**Comment by DM-netizen** [comment]
@joyhughes Can I take up this issue?

**Comment by joyhughes** [comment]
> @joyhughes Can I take up this issue?

Yes it's yours.  I'm a little uncertain exactly how to do this, so you can start by doing some research.

**Comment by DM-netizen** [comment]
Okkk👍

**Comment by DM-netizen** [comment]
Will I create a completely new vector field or modify the existing spiral one?

**Comment by DM-netizen** [comment]
Should I update every v in img.base with the corresponding values of n+1?
And also I am not clear whether to add position_fill() or not

**Comment by joyhughes** [comment]
Update every vector in the field. Calculate n in floating point. It is not necessary to call position_fill(), radial(), or cartesian() - assume the vector field is already in radial coordinates and include a comment describing that.
________________________________

**Comment by DM-netizen** [comment]
Ok
I wrote this:

```
void vf_tools::fermat_spiral(const float& c)
{
    for( auto& v : img.base )               //Taking every vector in polar form
    {
        v.x= c * sqrtf(powf(v.x/c,2)+1.0);
        v.y=v.y+ 137.508;
    }
}
```

**Comment by DM-netizen** [comment]
@joyhughes Does it need any changes?

**Comment by joyhughes** [comment]
This should probably work. I would use `const float& c` instead of `float c`
Did you put the function in the header vector_field.hpp and write the effect?
I will show you how to add it to scene_io.cpp

**Comment by DM-netizen** [comment]
Ok I will change that to `const float& c`
I have written the function header in `vector_field.hpp` but the effect one is left.

**Comment by DM-netizen** [comment]
in effect.hpp

```
template< class T > struct eff_fermat_spiral {
    harness< float > c;

    void operator () ( any_buffer_pair_ptr& buf, element_context& context );

    eff_fermat_spiral(float const_init = 0.0f ) : c( const_init ){}
};

typedef eff_fermat_spiral< vec2f > eff_fermat_spiral_vec2f;
```

in effect.cpp

```
template< class T > void eff_fermat_spiral< T >::operator () ( any_buffer_pair_ptr& buf, element_context& context )
{
    c(context);
    vf_tools tools( get_image< T >( buf ) );
    tools.fermat_spiral( *c );
}

template class eff_fermat_spiral< vec2f >;
```

Is this ok?

**Comment by joyhughes** [comment]
@DM-netizen This looks correct!

**Comment by joyhughes** [comment]
Now look in scene_io.cpp under the comment `// vector field effects` - I use macros there to make it easy to add new effects. You should be able to figure out how to add the effect there. Then I will show you how to make a scene file to test.

**Comment by DM-netizen** [comment]
`EFF( eff_fermat_spiral_vec2f ) HARNESSE( c ) END_EFF()`

I added this in `scene_io.cpp`

**Comment by DM-netizen** [comment]
I have some work coming up. So it will be really nice if you let me know how to proceed so that I can complete working on this at the earliest.

**Comment by joyhughes** [comment]
Please submit a PR
________________________________

**Comment by joyhughes** [comment]
One thing I forgot to mention is the need to add Fermat spiral into the variant `any_effect_fn_ptr` in  any_effect.hpp ... I have done this and will add it in a commit to the PR

**Comment by joyhughes** [comment]
@DM-netizen 
I'm so sorry - I'm having trouble merging this PR with the changes that I made. Could you make another PR off of current main branch and include your changes? Since this will be extra effort I will bump the issue up to level 3.

**Comment by DM-netizen** [comment]
Okk I  am doing it
