### ISSUE TITLE
fix security flaws from dependabot

### ISSUE THREAD

**Issue by rudi-cilibrasi** [joyhughes/Jen#144]
https://github.com/joyhughes/Jen/security/dependabot

**Comment by joyhughes** [comment]
@rudi-cilibrasi you can add the tags level1 (10 points), level2 (30 points), or level3 (45 points) depending on the complexity of the task. Without one of these tags the issue is worth only one point. Maybe bump it up a level if you think this is high severity.

**Comment by rudi-cilibrasi** [comment]
i will put level 3 assuming somebody fixes all. if somebody only does the most critical it is level 1.

**Comment by joyhughes** [comment]
Is it possible the move to Vite will resolve some of these?

**Comment by joyhughes** [comment]
The move to Vite (PR #152 ) fixed the two security issues including the one with "critical" severity. Seven issues remain.
