### ISSUE TITLE
problem compiling with g++ 12

### ISSUE THREAD

**Issue by rudi-cilibrasi** [joyhughes/Jen#18]
I'm getting compile errors with g++12 and also g++-11 under Ubuntu 22.04

seems like this project is only compiling with clang at the moment

see attached

[gcc-11-bug.txt](https://github.com/joyhughes/Jen/files/8838057/gcc-11-bug.txt)

**Comment by rudi-cilibrasi** [comment]
maybe this is problem https://stackoverflow.com/questions/54623100/c-gcc-floorf-not-a-member-of-std

**Comment by joyhughes** [comment]
In C++ 11, math functions such as `floor()` are overloaded to accept floating-point parameters without performance penalty. Therefore, reverting from using floating point specific functions such as `floorf()` to the overloaded versions should fix the portability issue.
 
 Issue will be closed upon a successful test.

**Comment by joyhughes** [comment]
Compilation also required adding some std includes
