### ISSUE TITLE
Widget group scrolling in interface container

### ISSUE THREAD

**Issue by joyhughes** [joyhughes/Jen#70]
This applies when control panel is to the right of image port. If the total height of all widget groups combined exceeds space available in the interface container, place a scroll bar to the right and allow user to scroll through the list of widgets of all groups except for the home group. The home group should be sticky, remain at the top, and not scroll.

**Comment by lassmara** [comment]
please assign me this issue

**Comment by joyhughes** [comment]
> please assign me this issue

@lassmara I think I have just fixed this issue. Perhaps you would like to work on a different issue.
