### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by Princegupta101** [joyhughes/Jen#97]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by joyhughes** [comment]
> I would like to work on this issue. Please assign me this task.

I assigned to you. Please include a standard code of conduct.

**Comment by suhanipaliwal** [comment]
I have started working on this issue. Could you please label this issue under GSSOC'24 and also label an appropriate level like Level 1, 2 or 3.

**Comment by joyhughes** [comment]
> I have started working on this issue. Could you please label this issue under GSSOC'24 and also label an appropriate level like Level 1, 2 or 3.

Done
