### ISSUE TITLE
project needs Dockerfile

### ISSUE THREAD

**Issue by rudi-cilibrasi** [joyhughes/Jen#99]
i noticed many devs want to contribute to this project. it could help people onboard if there was a Dockerfile that built an image that could at least build the project. ideally it could also serve in a dev test mode from within the docker container.

**Comment by joyhughes** [comment]
Note this is nearly identical to issue #68 - clearly it is important for devs to be able to build the project - close to or on the same level as getting the UI stable enough for a deployment

@rudi-cilibrasi would you like this issue? You seem to be good at devops-y things like this.
